services :
  frontend : 
    build : ./MyBookStore-main
    ports : 
      - "3001:80"
    restart : unless-stopped
    healthcheck :
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s