basePath: /api/v1
definitions:
  handler.Book:
    properties:
      id:
        type: integer
      title:
        type: string
    type: object
  handler.ErrorResponse:
    properties:
      message:
        type: string
    type: object
host: localhost:9999
info:
  contact: {}
  description: This is a simple example of using Gin with Swagger.
  title: Simple API Example
  version: "1.0"
paths:
  /books/{id}:
    get:
      description: Get details of a book by ID
      parameters:
      - description: Book ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/handler.Book'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/handler.ErrorResponse'
      summary: Get book by ID
      tags:
      - Books
swagger: "2.0"
